### ISSUE TITLE
bump the version please

### ISSUE THREAD

**Issue by michaelglass** [jpignata/temping#10]
I'd like to have access to that last commit, removing the hard dependency on sqlite

**Comment by JacobEvelyn** [comment]
Me too!

**Comment by kitop** [comment]
Just bumped the version on github and added a tag, but @jpignata is the one that can push to rubygems.

Meanwhile, if you use bundler you can do something like:
```ruby
gem 'temping', github: 'jpignata/temping', ref: 'v3.2.1'
```

**Comment by JacobEvelyn** [comment]
Thanks @kitop!

**Comment by JacobEvelyn** [comment]
Just noting for @jpignata that a new RubyGems version would still be awesome as I'm hoping to release a gem soon that has this as a development dependency, and the `github: ...` format isn't supported by `gemspec` files.

**Comment by fredngo** [comment]
+1 for new release please!
