### ISSUE TITLE
How to use Temping with a has_many model concern?

### ISSUE THREAD

**Issue by oniofchaos** [jpignata/temping#19]
Hi all,

I am trying to use Temping to test a model concern that has a `has_many` concern, but am running into an issue. My code looks something like this:

```
# lib/my_module/models/concerns/commentable.rb
module MyModule
  module Models
    module Commentable
      extend ActiveSupport::Concern

      included do
        has_many :comments, as: :commentable, dependent: :destroy
      end
    end
  end 
end

# lib/my_module/models/comment.rb
module MyModule
  module Models
    class Comment < ActiveRecord::Base
      # model code
    end
  end
end

# spec/models/concerns/commentable_spec.rb
# include MyModule::Models statement is in my spec_helper.rb
RSpec.describe Commentable do
  Temping.create :commentable_double do
    include Commentable
  end

  let(:model) { CommentableDouble.create! }

  it 'has many comments' do
    expect(model.comments).to be_a ActiveRecord::Associations::CollectionProxy
  end

  # more specs
end 
```

and I run into the following error:
```
Failure/Error: expect(model.comments).to be_a ActiveRecord::Associations::CollectionProxy
     NameError:
       uninitialized constant CommentableDouble::Comment
```

What can I do to fix this?

Note: Within the `Commentable` concern, I can't use `class_name: 'MyModule::Models::Comment'` as other parts of the application need the class name to be dynamic.

**Comment by shicholas** [comment]
:+1:

**Comment by supremebeing7** [comment]
I am doing something similar but it is working for me. Two caveats: 1) I'm working within rails so my models are in `app/models`, and 2) I'm not doing anything polymorphic.

I see you said `include MyModule::Models statement is in my spec_helper.rb`, but have you tried explicitly including the concern with the full namespacing?

    Temping.create :commentable_double do
      include MyModule::Models::Commentable
    end

Other than that I don't know. I can post my code if you think it will help.
