### ISSUE TITLE
Automate multi-database testing

### ISSUE THREAD

**Issue by gregnavis** [jpignata/temping#21]
# Problem

Currently the test suite uses an in-memory SQLite database. However, the library should be tested against multiple database adapters. The adapters are _not_ functionally equivalent. For instance, while implementing #20, I run into issue where `ActiveRecord::ConnectionAdapters::SQLite3Adapter#tables` does not list temporary tables while the corresponding methods of the MySQL and PostgreSQL adapters do. That can cause the tests pass for some databases and fail for others.
# Solution

We need a way of:
- setting up the database
- running the test suite for each adapter
- running the test suite with a single specified adapter

@kitop, @jpignata what are your thoughts on this?

**Comment by kitop** [comment]
@grn love the idea.

I think it could be possible to do something based on environment variables, so it's easy to run locally and in the CI server (we're using Travis now).
Maybe we can take some ideas from here: http://docs.travis-ci.com/user/languages/ruby/#Testing-against-multiple-versions-of-dependencies-(Ruby-on-Rails%2C-EventMachine%2C-etc)

What do you think?

**Comment by dmytro-savochkin** [comment]
I've added multi database testing in Github Actions in the scope of https://github.com/jpignata/temping/pull/62 so closing this issue as fixed.
