### ISSUE TITLE
Make multi-database tests work in JRuby

### ISSUE THREAD

**Issue by gregnavis** [jpignata/temping#23]
# Problem

Currently, multi-database tests (see #21 and the corresponding pull request #22) work only in MRI.
# Solution

Add the missing JRuby dependencies and ensure the test suite works.

**Comment by dmytro-savochkin** [comment]
I've added multi database testing in Github Actions (including jruby) in the scope of https://github.com/jpignata/temping/pull/62 so closing this issue as fixed.
