### ISSUE TITLE
Possibility to use a custom primary key

### ISSUE THREAD

**Issue by jacopo-beschi-intersail** [jpignata/temping#26]
Could you add the possibility to use a custom primary key? 

Best

**Comment by kitop** [comment]
@jacopo-beschi-intersail what would be your use case? Do you have an example?

**Comment by kitop** [comment]
Hey @jacopo-beschi-intersail #38 should have fixed the problem. The change was released in version 3.4.0.
Does that help?

**Comment by intrip** [comment]
Yes, that solves the problem. Thanks.

**Comment by kitop** [comment]
Great!
Closing this.
