### ISSUE TITLE
Support MySQL and Oracle

### ISSUE THREAD

**Issue by martndemus** [jpignata/temping#27]
Both MySQL and Oracle commit the current transaction when you execute DDL statements.
Temping executes DDL statements during a test, ergo: the data created during a test is committed because the test suite can't rollback the transaction created for the test.

Issue #15 is one symptom of this.

It would be cool if support for this problem would be added!

**Comment by kitop** [comment]
As mentioned in #15, calling `Temping.teardown` before rolling back the transaction fixes the issue.
