### ISSUE TITLE
Testing Travis error for Ruby 2.1

### ISSUE THREAD

**Issue by gmoseson** [jpignata/temping#36]
When trying to deploy, I got this error in Travis https://travis-ci.org/jpignata/temping/jobs/115696553.

Added 
before_install:
  - gem install bundler 
to .travis.yml to see if it fixes the error.

**Comment by kitop** [comment]
It should be working now. That seems an issue with bundler itself.
Are you still getting the same error still?

**Comment by gmoseson** [comment]
No it seems to be working now.
