### ISSUE TITLE
Create table without primary_key

### ISSUE THREAD

**Issue by TylerJBrown192** [jpignata/temping#42]
Is this possible? If I try to pass in an `:id => false` flag where it would correctly go in a regular ActiveRecord create_table() method and I get the error

`ActiveRecord::StatementInvalid: Mysql2::Error: A table must have at least 1 column: CREATE TEMPORARY TABLE `circulation_models` ENGINE=InnoDB`

I have also crawled into the gem itself and changed it to no avail.

**Comment by kitop** [comment]
@TylerJBrown192 how are you trying to create the table? Can you paste some example code here?

For what I can understand in the error message, seems like it wants to create a table with no columns at all.
