### ISSUE TITLE
Can't get attribute_names

### ISSUE THREAD

**Issue by jfpimentel** [jpignata/temping#51]
I'm trying to create a spec for this concern:
```
require "active_support/concern"

module ModuleA
  extend ActiveSupport::Concern

  included do
    do_something
  end

  class_methods do
    def do_something
      puts attribute_names # it will only print id :(
    end
  end
end
```

And the spec looks like this:

```
require "rails_helper"

RSpec.describe ModuleA do
  before(:all) do
    Temping.create :thing do
      include ModuleA

      with_columns do |t|
        t.boolean :attribute, default: false
      end
    end
  end

  it "does something" do
    ...
  end
end
```
The problem is: when I try to get the `attribute_names` it will only have `id`...
Any ideas why `attribute` is missing?

**Comment by kitop** [comment]
Have you tried including `ModuleA` after the `with_columns` block?
Becase `do_something` runs when the module is included, that is before the columns are defined thus not having `attribute`.

**Comment by jfpimentel** [comment]
Yep, that was it :sweat_smile:
Thanks!
