### ISSUE TITLE
Rails 5 compatibility?

### ISSUE THREAD

**Issue by mmhan** [jpignata/temping#55]
Has this been tested with Rails 5? I was updating my app and Temping models are failing rspecs.

Please let me know if you need more info.

**Comment by kitop** [comment]
Hi @mmhan. It hasn't been tested with Rails 5 yet. But we can work on an upgrade.

Can you provide more info on the errors you were getting? Thanks!

**Comment by kitop** [comment]
I just updated the CI config so it tests with ruby 2.2+ and Rails 4.2+, and all tests are passing in Travis.

More info on the failures you're getting would be very helpful!

**Comment by mmhan** [comment]
I'm on Ruby 2.3 and rails 5.0. Can you try with it on your CI config?

**Comment by kitop** [comment]
Tests are passing with that combination: https://travis-ci.org/jpignata/temping/jobs/264692349

Can you create a repo with the minimal setup to reproduce the error?

**Comment by mmhan** [comment]
Will do, gimme a few days.

**Comment by kitop** [comment]
Thanks!

**Comment by mmhan** [comment]
Just created a new rails project and tested it. It's running without any errors on that project. Please consider this issue closed. I, however, will be creating a separate issue for the error that I'm facing.

**Comment by mmhan** [comment]
https://github.com/mmhan/TempingRails5 is the link to my test repo

**Comment by mmhan** [comment]
The following is the error I received when I ran the full suite in my main project.

```
Mysql2::Error: Table 'project_name_test.expirable_listings' doesn't exist: SHOW FULL FIELDS FROM `expirable_listings`
```

**Comment by kitop** [comment]
Hi @mmhan I just cloned your repo, created the database, and run the tests successfully with no errors.

May I ask what version of mysql are you running?

**Comment by mmhan** [comment]
Hey @kitop - The error that I'm facing isn't on the repo that I have given you.

The environment that I am facing the error is on

```
MacOSX 10.12.6
MySQL 5.6.19

# Gems
database_cleaner 1.5.1
rspec-rails 3.6.1
```

**Comment by kitop** [comment]
Oh sorry! Misunderstood that. Will close this and wait for the new issue to help debug. And thanks for the info on the environment, will be helpful for the other issue.
